version: '3'

services:
  api:
    image: go-default:1.0.0
    environment:
      - TZ=Asia/Shanghai
      - CONFIG_PATH_PREFIX=/app/src/config/

      - Slogan=安全APP
      - WeixinAppID=<WeixinAppID>
      - WeixinAppSecret=<WeixinAppSecret>

      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=<PASSWORD>
      - MONGO_INITDB_DATABASE=secure_app

      - RedisPass=<PASSWORD>

      - QINIU_ACCESS_KEY=<QINIU_ACCESS_KEY>
      - QINIU_SECRET_KEY=<QINIU_SECRET_KEY>
      - QINIU_BUCKET=secure-app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./src:/app/src
      - ./log:/app/log
    ports:
      - "6556:3000"
      - "49273:3001"
    depends_on:
      - redis
      - mongo
    container_name: secure-app-api
    entrypoint: go run src/main.go
    logging:
      driver: gelf
      options:
        gelf-address: '<adress>'
        tag: secure-app
  mongo:
    image: mongo:3.6.3
    expose:
      - "27017"
    ports:
      - "49270:27017"
    volumes:
      - ./data/mongo:/data/db
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=<PASSWORD>
      - MONGO_INITDB_DATABASE=secure_app
    container_name: secure-app-mongo
  redis:
    image: redis:4.0.8
    ports:
      - "49271:6379"
    environment:
      - TZ=Asia/Shanghai
      - RedisPass=<PASSWORD>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    container_name: secure-app-redis
