// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReqHeader struct {
	AuthToken            string   `protobuf:"bytes,1,opt,name=AuthToken,proto3" json:"AuthToken,omitempty"`
	ReqMethod            string   `protobuf:"bytes,2,opt,name=ReqMethod,proto3" json:"ReqMethod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqHeader) Reset()         { *m = ReqHeader{} }
func (m *ReqHeader) String() string { return proto.CompactTextString(m) }
func (*ReqHeader) ProtoMessage()    {}
func (*ReqHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *ReqHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqHeader.Unmarshal(m, b)
}
func (m *ReqHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqHeader.Marshal(b, m, deterministic)
}
func (m *ReqHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqHeader.Merge(m, src)
}
func (m *ReqHeader) XXX_Size() int {
	return xxx_messageInfo_ReqHeader.Size(m)
}
func (m *ReqHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ReqHeader proto.InternalMessageInfo

func (m *ReqHeader) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

func (m *ReqHeader) GetReqMethod() string {
	if m != nil {
		return m.ReqMethod
	}
	return ""
}

type ResHeader struct {
	ResMethod            string   `protobuf:"bytes,2,opt,name=ResMethod,proto3" json:"ResMethod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResHeader) Reset()         { *m = ResHeader{} }
func (m *ResHeader) String() string { return proto.CompactTextString(m) }
func (*ResHeader) ProtoMessage()    {}
func (*ResHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *ResHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResHeader.Unmarshal(m, b)
}
func (m *ResHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResHeader.Marshal(b, m, deterministic)
}
func (m *ResHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResHeader.Merge(m, src)
}
func (m *ResHeader) XXX_Size() int {
	return xxx_messageInfo_ResHeader.Size(m)
}
func (m *ResHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResHeader proto.InternalMessageInfo

func (m *ResHeader) GetResMethod() string {
	if m != nil {
		return m.ResMethod
	}
	return ""
}

type Location struct {
	Longitude            float64  `protobuf:"fixed64,1,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Latitude             float64  `protobuf:"fixed64,2,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

//
//General Notes:
//- 请求数据和返回数据均使用 protobuf 序列化，语法为 proto3
//- 客户端和服务端的proto文件必须统一
//- 所有Request必须带有ReqMethod(请求方法), eg:SetUserLocEQ
//- 所有Response必须带有ResMethod(返回方法), eg:GetUserLocEQ
//- 所有Request必须带有AuthToken(jwt token)，token通过HTTP方法获得，所有socket数据交流都通过此Token进行验证
//
//有待商量：（暂未采用）
//- 所有数据进行序列化之后再使用对称加密进行一次加密
//- 暂定加密算法：AES CFB模式
//- 流程如下：
//- 首先通过HTTP方法的认证
//- 客户端通过HTTP形式获取对称加密密钥对（key, secret), key 为12个字符串
//- 所有数据进行proto序列化之后再将数据使用AES进行加密,同时在加密之后追加key
//- 服务端使用key在存储中获取secret
//- 使用secret对加密数据解密
//- 使用proto反序列化
//
//Request Notes:
//请求格式如下：
//- message: <ReqMethod>Req, eg: SetUserLocEQReq -> ReqMethod: SetUserLocEQ
//
//Response Notes:
//返回格式如下：
//- message: <ResMethod>Res, eg: GetUserLocEQRes -> ResMethod: GetUserLocEQ
type PingReq struct {
	Header               *ReqHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PingReq) Reset()         { *m = PingReq{} }
func (m *PingReq) String() string { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()    {}
func (*PingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *PingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReq.Unmarshal(m, b)
}
func (m *PingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReq.Marshal(b, m, deterministic)
}
func (m *PingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReq.Merge(m, src)
}
func (m *PingReq) XXX_Size() int {
	return xxx_messageInfo_PingReq.Size(m)
}
func (m *PingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReq.DiscardUnknown(m)
}

var xxx_messageInfo_PingReq proto.InternalMessageInfo

func (m *PingReq) GetHeader() *ReqHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type PingRes struct {
	Header               *ResHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PingRes) Reset()         { *m = PingRes{} }
func (m *PingRes) String() string { return proto.CompactTextString(m) }
func (*PingRes) ProtoMessage()    {}
func (*PingRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *PingRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRes.Unmarshal(m, b)
}
func (m *PingRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRes.Marshal(b, m, deterministic)
}
func (m *PingRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRes.Merge(m, src)
}
func (m *PingRes) XXX_Size() int {
	return xxx_messageInfo_PingRes.Size(m)
}
func (m *PingRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRes.DiscardUnknown(m)
}

var xxx_messageInfo_PingRes proto.InternalMessageInfo

func (m *PingRes) GetHeader() *ResHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type SetUserLocEQReq struct {
	Header               *ReqHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Loc                  *Location  `protobuf:"bytes,5,opt,name=Loc,proto3" json:"Loc,omitempty"`
	EQ                   int32      `protobuf:"varint,6,opt,name=EQ,proto3" json:"EQ,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SetUserLocEQReq) Reset()         { *m = SetUserLocEQReq{} }
func (m *SetUserLocEQReq) String() string { return proto.CompactTextString(m) }
func (*SetUserLocEQReq) ProtoMessage()    {}
func (*SetUserLocEQReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}

func (m *SetUserLocEQReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserLocEQReq.Unmarshal(m, b)
}
func (m *SetUserLocEQReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserLocEQReq.Marshal(b, m, deterministic)
}
func (m *SetUserLocEQReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserLocEQReq.Merge(m, src)
}
func (m *SetUserLocEQReq) XXX_Size() int {
	return xxx_messageInfo_SetUserLocEQReq.Size(m)
}
func (m *SetUserLocEQReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserLocEQReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserLocEQReq proto.InternalMessageInfo

func (m *SetUserLocEQReq) GetHeader() *ReqHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SetUserLocEQReq) GetLoc() *Location {
	if m != nil {
		return m.Loc
	}
	return nil
}

func (m *SetUserLocEQReq) GetEQ() int32 {
	if m != nil {
		return m.EQ
	}
	return 0
}

type GetUserLocEQReq struct {
	Header               *ResHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	UserID               string     `protobuf:"bytes,5,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetUserLocEQReq) Reset()         { *m = GetUserLocEQReq{} }
func (m *GetUserLocEQReq) String() string { return proto.CompactTextString(m) }
func (*GetUserLocEQReq) ProtoMessage()    {}
func (*GetUserLocEQReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{6}
}

func (m *GetUserLocEQReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserLocEQReq.Unmarshal(m, b)
}
func (m *GetUserLocEQReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserLocEQReq.Marshal(b, m, deterministic)
}
func (m *GetUserLocEQReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserLocEQReq.Merge(m, src)
}
func (m *GetUserLocEQReq) XXX_Size() int {
	return xxx_messageInfo_GetUserLocEQReq.Size(m)
}
func (m *GetUserLocEQReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserLocEQReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserLocEQReq proto.InternalMessageInfo

func (m *GetUserLocEQReq) GetHeader() *ResHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetUserLocEQReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetUserLocEQRes struct {
	Header               *ResHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Status               int32      `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
	Loc                  *Location  `protobuf:"bytes,5,opt,name=Loc,proto3" json:"Loc,omitempty"`
	EQ                   int32      `protobuf:"varint,6,opt,name=EQ,proto3" json:"EQ,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetUserLocEQRes) Reset()         { *m = GetUserLocEQRes{} }
func (m *GetUserLocEQRes) String() string { return proto.CompactTextString(m) }
func (*GetUserLocEQRes) ProtoMessage()    {}
func (*GetUserLocEQRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{7}
}

func (m *GetUserLocEQRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserLocEQRes.Unmarshal(m, b)
}
func (m *GetUserLocEQRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserLocEQRes.Marshal(b, m, deterministic)
}
func (m *GetUserLocEQRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserLocEQRes.Merge(m, src)
}
func (m *GetUserLocEQRes) XXX_Size() int {
	return xxx_messageInfo_GetUserLocEQRes.Size(m)
}
func (m *GetUserLocEQRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserLocEQRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserLocEQRes proto.InternalMessageInfo

func (m *GetUserLocEQRes) GetHeader() *ResHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetUserLocEQRes) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetUserLocEQRes) GetLoc() *Location {
	if m != nil {
		return m.Loc
	}
	return nil
}

func (m *GetUserLocEQRes) GetEQ() int32 {
	if m != nil {
		return m.EQ
	}
	return 0
}

type AddShareCTRes struct {
	Header               *ResHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	UserID               string     `protobuf:"bytes,5,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AddShareCTRes) Reset()         { *m = AddShareCTRes{} }
func (m *AddShareCTRes) String() string { return proto.CompactTextString(m) }
func (*AddShareCTRes) ProtoMessage()    {}
func (*AddShareCTRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{8}
}

func (m *AddShareCTRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddShareCTRes.Unmarshal(m, b)
}
func (m *AddShareCTRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddShareCTRes.Marshal(b, m, deterministic)
}
func (m *AddShareCTRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddShareCTRes.Merge(m, src)
}
func (m *AddShareCTRes) XXX_Size() int {
	return xxx_messageInfo_AddShareCTRes.Size(m)
}
func (m *AddShareCTRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AddShareCTRes.DiscardUnknown(m)
}

var xxx_messageInfo_AddShareCTRes proto.InternalMessageInfo

func (m *AddShareCTRes) GetHeader() *ResHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *AddShareCTRes) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

// 客户端请求消息队列
type GetMsgQueneReq struct {
	Header               *ResHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetMsgQueneReq) Reset()         { *m = GetMsgQueneReq{} }
func (m *GetMsgQueneReq) String() string { return proto.CompactTextString(m) }
func (*GetMsgQueneReq) ProtoMessage()    {}
func (*GetMsgQueneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{9}
}

func (m *GetMsgQueneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMsgQueneReq.Unmarshal(m, b)
}
func (m *GetMsgQueneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMsgQueneReq.Marshal(b, m, deterministic)
}
func (m *GetMsgQueneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMsgQueneReq.Merge(m, src)
}
func (m *GetMsgQueneReq) XXX_Size() int {
	return xxx_messageInfo_GetMsgQueneReq.Size(m)
}
func (m *GetMsgQueneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMsgQueneReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMsgQueneReq proto.InternalMessageInfo

func (m *GetMsgQueneReq) GetHeader() *ResHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GetMsgQueneRes struct {
	Header               *ResHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Data                 [][]byte   `protobuf:"bytes,5,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetMsgQueneRes) Reset()         { *m = GetMsgQueneRes{} }
func (m *GetMsgQueneRes) String() string { return proto.CompactTextString(m) }
func (*GetMsgQueneRes) ProtoMessage()    {}
func (*GetMsgQueneRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{10}
}

func (m *GetMsgQueneRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMsgQueneRes.Unmarshal(m, b)
}
func (m *GetMsgQueneRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMsgQueneRes.Marshal(b, m, deterministic)
}
func (m *GetMsgQueneRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMsgQueneRes.Merge(m, src)
}
func (m *GetMsgQueneRes) XXX_Size() int {
	return xxx_messageInfo_GetMsgQueneRes.Size(m)
}
func (m *GetMsgQueneRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMsgQueneRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetMsgQueneRes proto.InternalMessageInfo

func (m *GetMsgQueneRes) GetHeader() *ResHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetMsgQueneRes) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ErrorRes struct {
	Header               *ResHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Status               int32      `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	ErrMsg               string     `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ErrorRes) Reset()         { *m = ErrorRes{} }
func (m *ErrorRes) String() string { return proto.CompactTextString(m) }
func (*ErrorRes) ProtoMessage()    {}
func (*ErrorRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{11}
}

func (m *ErrorRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorRes.Unmarshal(m, b)
}
func (m *ErrorRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorRes.Marshal(b, m, deterministic)
}
func (m *ErrorRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorRes.Merge(m, src)
}
func (m *ErrorRes) XXX_Size() int {
	return xxx_messageInfo_ErrorRes.Size(m)
}
func (m *ErrorRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorRes.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorRes proto.InternalMessageInfo

func (m *ErrorRes) GetHeader() *ResHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ErrorRes) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ErrorRes) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqHeader)(nil), "model.ReqHeader")
	proto.RegisterType((*ResHeader)(nil), "model.ResHeader")
	proto.RegisterType((*Location)(nil), "model.Location")
	proto.RegisterType((*PingReq)(nil), "model.PingReq")
	proto.RegisterType((*PingRes)(nil), "model.PingRes")
	proto.RegisterType((*SetUserLocEQReq)(nil), "model.SetUserLocEQReq")
	proto.RegisterType((*GetUserLocEQReq)(nil), "model.GetUserLocEQReq")
	proto.RegisterType((*GetUserLocEQRes)(nil), "model.GetUserLocEQRes")
	proto.RegisterType((*AddShareCTRes)(nil), "model.AddShareCTRes")
	proto.RegisterType((*GetMsgQueneReq)(nil), "model.GetMsgQueneReq")
	proto.RegisterType((*GetMsgQueneRes)(nil), "model.GetMsgQueneRes")
	proto.RegisterType((*ErrorRes)(nil), "model.ErrorRes")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xc1, 0x4e, 0xeb, 0x30,
	0x10, 0x54, 0xd2, 0x97, 0xbc, 0x66, 0x5f, 0x5f, 0x8b, 0x7c, 0xa8, 0x22, 0xc4, 0xa1, 0xf8, 0x14,
	0x2e, 0x3d, 0xd0, 0x1b, 0xb7, 0x8a, 0x46, 0x05, 0x29, 0x45, 0xc4, 0x29, 0x1f, 0x10, 0xe2, 0x55,
	0x5a, 0x41, 0x63, 0x6a, 0x3b, 0xbf, 0xc0, 0x77, 0xa3, 0xb8, 0xa1, 0x11, 0x11, 0x42, 0xa4, 0x37,
	0xef, 0xce, 0xce, 0xcc, 0xce, 0x4a, 0x86, 0x41, 0x26, 0x76, 0x3b, 0x51, 0x4c, 0xdf, 0xa4, 0xd0,
	0x82, 0x38, 0x3b, 0xc1, 0xf1, 0x95, 0x2e, 0xc1, 0x63, 0xb8, 0xbf, 0xc3, 0x94, 0xa3, 0x24, 0x17,
	0xe0, 0xcd, 0x4b, 0xbd, 0x59, 0x8b, 0x17, 0x2c, 0x7c, 0x6b, 0x62, 0x05, 0x1e, 0x6b, 0x1a, 0x15,
	0xca, 0x70, 0xbf, 0x42, 0xbd, 0x11, 0xdc, 0xb7, 0x0f, 0xe8, 0xb1, 0x41, 0xaf, 0x2a, 0x54, 0x35,
	0x42, 0x0c, 0x55, 0x7b, 0xb4, 0x6e, 0xd0, 0x05, 0xf4, 0x23, 0x91, 0xa5, 0x7a, 0x2b, 0x8c, 0x68,
	0x24, 0x8a, 0x7c, 0xab, 0x4b, 0x8e, 0xc6, 0xd2, 0x62, 0x4d, 0x83, 0x9c, 0x43, 0x3f, 0x4a, 0xf5,
	0x01, 0xb4, 0x0d, 0x78, 0xac, 0xe9, 0x0c, 0xfe, 0x3e, 0x6e, 0x8b, 0x9c, 0xe1, 0x9e, 0x04, 0xe0,
	0x1e, 0x8c, 0x8d, 0xc2, 0xbf, 0xeb, 0xb3, 0xa9, 0x09, 0x37, 0x3d, 0x26, 0x63, 0x35, 0xde, 0x90,
	0xd4, 0x0f, 0x24, 0xd5, 0x22, 0x15, 0x30, 0x4a, 0x50, 0x3f, 0x29, 0x94, 0x91, 0xc8, 0xc2, 0xb8,
	0x93, 0x23, 0xb9, 0x84, 0x5e, 0x24, 0x32, 0xdf, 0x31, 0x63, 0xa3, 0x7a, 0xec, 0x33, 0x3e, 0xab,
	0x30, 0x32, 0x04, 0x3b, 0x8c, 0x7d, 0x77, 0x62, 0x05, 0x0e, 0xb3, 0xc3, 0x98, 0x26, 0x30, 0x5a,
	0xfe, 0xda, 0xaf, 0xb5, 0x2c, 0x19, 0x83, 0x5b, 0x31, 0xef, 0x17, 0xc6, 0xd2, 0x63, 0x75, 0x45,
	0xdf, 0xad, 0xb6, 0xaa, 0xea, 0xa6, 0x9a, 0xe8, 0x54, 0x97, 0xca, 0xef, 0x99, 0x35, 0xeb, 0xea,
	0x94, 0x74, 0x31, 0xfc, 0x9f, 0x73, 0x9e, 0x6c, 0x52, 0x89, 0xb7, 0xeb, 0xce, 0x5b, 0x7c, 0x9b,
	0xed, 0x06, 0x86, 0x4b, 0xd4, 0x2b, 0x95, 0xc7, 0x25, 0x16, 0xd8, 0xe9, 0x5e, 0xf4, 0xa1, 0xc5,
	0xed, 0xb2, 0x0f, 0x81, 0x3f, 0x8b, 0x54, 0xa7, 0xbe, 0x33, 0xe9, 0x05, 0x03, 0x66, 0xde, 0x94,
	0x43, 0x3f, 0x94, 0x52, 0xc8, 0x53, 0xef, 0x6b, 0x7f, 0xb9, 0xef, 0x18, 0xdc, 0x50, 0xca, 0x95,
	0xca, 0xcd, 0xdd, 0x3d, 0x56, 0x57, 0xcf, 0xae, 0xf9, 0xc4, 0xb3, 0x8f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x6e, 0x8b, 0x07, 0x61, 0xd4, 0x03, 0x00, 0x00,
}
